import axios from 'axios'

let veo2 = async (m, { conn: Ditss, text }) => {
  if (!text) return m.reply('Masukkan prompt untuk membuat video!\nContoh: .veo2 buatkan video kucing lucu')
  
  await Ditss.sendMessage(m.chat, { react: { text: "⏳", key: m.key } })
  
  const apiUrl = `${global.api.domain}/v1/tools/veo2?prompt=${encodeURIComponent(text)}&apikey=${global.api.key}`
  
  try {
    const response = await axios.get(apiUrl, {
      timeout: 120000,
      headers: { 'User-Agent': 'Mozilla/5.0' }
    })
    
    const data = response.data
    
    if (!data.status || !data.result || !data.result.video_url) {
      await Ditss.sendMessage(m.chat, { react: { text: "❌", key: m.key } })
      return m.reply('❌ Gagal membuat video')
    }
    
    const { video_url, prompt } = data.result
    
    const videoResponse = await axios.get(video_url, {
      responseType: 'arraybuffer',
      timeout: 60000
    })
    
    const videoBuffer = Buffer.from(videoResponse.data)
    
    if (videoBuffer.length === 0) {
      return m.reply('❌ Video kosong atau tidak valid')
    }
    
    if (videoBuffer.length > 50 * 1024 * 1024) {
      return m.reply(`❌ Video terlalu besar (${(videoBuffer.length / (1024 * 1024)).toFixed(2)} MB)\n\nSilakan download manual:\n${video_url}`)
    }
    
    await Ditss.sendMessage(m.chat, {
      video: videoBuffer,
      caption: `🎬 *VE02 AI Video*\n\n📝 *Prompt:* ${prompt}\n⏱️ *Waktu proses:* ${data.responseTime}\n\nGenerated by @${global.info?.namabot || 'Bot'}`
    }, { quoted: m })
    
    await Ditss.sendMessage(m.chat, { react: { text: "✅", key: m.key } })
    
  } catch (error) {
    await Ditss.sendMessage(m.chat, { react: { text: "❌", key: m.key } })
    
    if (error.code === 'ECONNABORTED') {
      m.reply('❌ Timeout: Server terlalu lama merespon (lebih dari 2 menit)')
    } else if (error.response?.status === 404) {
      m.reply('❌ Video tidak ditemukan atau sudah dihapus dari server')
    } else if (error.response) {
      m.reply(`❌ Error ${error.response.status}: Gagal membuat video`)
    } else if (error.code === 'ENOTFOUND') {
      m.reply('❌ Server API tidak dapat diakses')
    } else {
      m.reply(`❌ Error: ${error.message}`)
    }
  }
}

veo2.help = ['veo2 <prompt>']
veo2.tags = ['ai', 'video']
veo2.command = ['veo2', 'veo']

export default veo2
